### ISSUE TITLE
reproduce some results

### ISSUE THREAD

**Issue by Ulitochka** [deep-spin/SIGMORPHON2019#1]
Hello.

Thank you for your work.

I would like to reproduce your systems result in turk-azeri (task 1).

Could you help me?
My question is: that config-file from catalog 'config' I must use to reproduce this submit?

**Comment by bpopeters** [comment]
Hello and thank you for your interest! In order to reproduce the Turkish-Azeri results, you can

1. Preprocess the data. Make sure you are in the project directory and run 

```python preprocess.py -train path/to/sigmorphon/2019/task1/turkish--azeri/*train* -valid path/to/sigmorphon/2019/task1/turkish--azeri/azeri-dev -save_data path/to/data -low_oversampling 100 -multilingual --inflection_field```

where `path/to/sigmorphon/2019/` is replaced by the path where you cloned the [SIGMORPHON 2019 repository](https://github.com/sigmorphon/2019/) and `path/to/data` is replaced by the path you want to save the preprocessed data to.

2. Train the data. If you would like to train the model called DoubleAttn in the paper, you can use

```python train.py -save_model path/to/save -data path/to/data -config config/double-attn-sparse/dropout03.yml```

or if you would prefer the GatedAttn,

```python train.py -save_model path/to/save -data path/to/data -config config/separate-gate-sparse/dropout03.yml```

In either case, you should replace `path/to/save` with the prefix of the name you would like all saved models to have. So if you use `save_model tk-az-model`, then the saved models will have names like `tk-az-model_epoch17.pt` and will be located in this repo's main directiory.

3. Use one of the models to translate

```python translate.py -model path/to/some/model.pt -corpus path/to/sigmorphon/2019/task1/turkish--azeri/azeri-dev -output path/to/output.txt```

You may also be interested in the `-verbose` flag or experimenting with different beam sizes when translating.

Hope that helps!

**Comment by Ulitochka** [comment]
Thanks for the answer!

And somewhere there is test data (with target (gold) forms) for task 1?

**Comment by bpopeters** [comment]
[Here](https://github.com/sigmorphon/2019/blob/75dbb844dec88dab54f8f53e8a71d49f70f07532/task1/turkish--azeri/azeri-test) you go. They released it a few months ago, then reverted releasing it, but the whole history of the repository is still visible.

**Comment by Ulitochka** [comment]
Thanks!!!

Cool! 

I use /config/separate-gate-sparse/dropout03.yml and on test I have results: acccuracy:	89.00	levenshtein:	0.25
I use the script that was provided by the organizers for calculate metrics.
¯\_(ツ)_/¯

**Comment by bpopeters** [comment]
Great, that's actually slightly better accuracy than the results I submitted to the shared task. The differences are probably down to using a different random seed.

**Comment by Ulitochka** [comment]
Have you fixed it somewhere?

**Comment by bpopeters** [comment]
Unfortunately not in the config I used. You can add a seed value to train.py on the command line or in the config.

**Comment by Ulitochka** [comment]
Thanks again for the cool work!
